site_name: XEL Network
pages:
    - XEL Network: index.md
    - OpenSource Hardware: hardware.md
    - OpenSource Software: software.md
    - Getting Start: getting_start.md
    - 한국 베타테스터 가이드 문서: getting_start_beta_kor.md
theme: readthedocs
