site_name: XEL Network
pages:
    - XEL Network: index.md
    - OpenSource Hardware: hardware.md
    - OpenSource Software: software.md
    - Getting Start: getting_start.md
    - Getting Start For Korean BetaTester: getting_start_beta_kor.md
theme: readthedocs
